export {default as Home} from './home.jsx'
export {default as LoginPage} from './login.jsx'
export {default as SignUpPage} from './signup.jsx'
export {default as NotFoundPage} from './404.jsx'
export {default as StudentDashboard} from './studentView.jsx'
export {default as TeacherDashboard} from './teacher.jsx'
export {default as TaDashboard} from './ta.jsx'
export {default as AboutPage} from './about.jsx'